### ISSUE TITLE
Continue researching CO2 models for transportation carbon estimation

### ISSUE THREAD

**Issue by brylie** [maasglobal/transport-co2#6]
As part of the 0.2 release cycle, we want to perform due diligence to try and find a recent/relevant model for transportation CO2 emissions.

## Task
Search multiple sources for transportation CO2 emissions model:
- [ ] peer-reviewed journals
- [ ] governmental agencies (e.g. EEA, US DOT, etc.)
- [ ] open-source software ecosystem

Document any efforts/findings in the project README.

**Comment by brylie** [comment]
This example was shared by @jpetsalo 
https://travelandmobility.tech/infographics/carbon-emissions-by-transport-type/

**Comment by brylie** [comment]
The [Simulation of Urban Mobility](https://projects.eclipse.org/projects/technology.sumo) project uses the [Handbook emission factors for road transport (HBEFA)](https://www.hbefa.net/e/index.html) for road vehicle emissions estimation.

**Comment by brylie** [comment]
There is an R package called [Vehicular Emissions Inventories (VEIN)](https://atmoschem.github.io/vein/) that estimates vehicle emissions.

**Comment by brylie** [comment]
The EU [Annual European Union greenhouse gas inventory (2019)](https://www.eea.europa.eu/publications/european-union-greenhouse-gas-inventory-2019) might have some useful footnotes or references to carbon models in various sectors.
